### POST dang ki
POST http://localhost:3000/api/accounts/signup
content-type: application/json

{
    "phone": "0927055639",
    "email": "daudangson123@gmail.com",
    "password": "123456",
    "name": "Daudang Son",
    "birthday": "1990-01-01",
    "address": "Hanoi"

}

### POST dang nhap
POST  http://localhost:3000/api/accounts/login
content-type: application/json

{
    "username": "5857549051",
    "password": "123456"
}

### 
POST  http://localhost:3000/api/accounts/login
content-type: application/json

{
    "username": "632456257",
    "password": "1234567"
}
### GET accounts view
GET http://localhost:3000/accounts

### POST deposit
POST http://localhost:3000/transactions/deposit
content-type: application/json